### PR TITLE
Cleaner Testplugin

### PR DESCRIPTION
**Pull request by yannicklamprecht**
- added some panel for direct usage
- get rid of complex getOverlayText method

### CODE REVIEW

**Comment by NickAcPT** [comment]
Thank you for your pull request.
Right now I'm on my phone, so I can't test this.
I just feel you are overly complicating simple stuff. :D
The original code was created just to test Lithium with the fastest way possible. Hence the non existent command registration and stupid code.
Since you've shown interest in Lithium, do you want to be a hero? I have some simple questions for you!

Do you want to create a GUI creator plugin for Lithium? (Using XML or something like that)
Or you could create some example plugins to show the power of Lithium. 
If you don't want to do either, I don't blame you!
I'll just thank you instead, for trying Lithium.

**Comment by yannicklamprecht** [comment]
> I just feel you are overly complicating simple stuff. :D

No just flatten the complexity of 
https://github.com/NickAcPT/Lithium-TestPlugin/blob/master/src/net/nickac/testing/lithium/OverlayPlayer.java#L58-L70
https://github.com/NickAcPT/Lithium-TestPlugin/blob/master/src/net/nickac/testing/lithium/OverlayPlayer.java#L73-L81


I thought about writing an extension for some DayZ specific stuff.
Like
https://i.ytimg.com/vi/hzeFNhc2MyM/maxresdefault.jpg

Is it possible to have a background behind text? Like multilayer rendering. Shown in the image for example.

**Comment by NickAcPT** [comment]
> No just flatten the complexity of
https://github.com/NickAcPT/Lithium-TestPlugin/blob/master/src/net/nickac/testing/lithium/OverlayPlayer.java#L58-L70
https://github.com/NickAcPT/Lithium-TestPlugin/blob/master/src/net/nickac/testing/lithium/OverlayPlayer.java#L73-L81

Thank you for your contribution.

> Is it possible to have a background behind text? Like multilayer rendering. Shown in the image for example.

Yes, that is possible, but we would need to swap some lines on the forge mod. I've looked through the files and the images are the ones to be rendered last. When possible, I'll release another RC version. Since it's 12:40 AM in my location, I can only do that later.

Thank you again for your interest. Also, don't forget that the interfaces will only be shown to players using the mod :D

**Comment by NickAcPT** [comment]
I'll open an issue regarding that.

**Comment by yannicklamprecht** [comment]
Good night. It's 1:44 at my location. Going to sleep as well.

**Pull request merged**
